<?php
/**
 * @file
 * Code for the News feature.
 */

include_once 'news.features.inc';

function news_menu() {

  $items['jeeveserp-layout/topitem/news'] = array(
    'page callback' => '_news_topitem_autocomplete',
    'access arguments' => array('reference top news'),
    'type' => MENU_CALLBACK
  );

  $items['admin/content/topitem-news'] = array(
    'title' => 'Reference top news item',
    'description' => 'Use top item picker for news',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('news_topitem_admin'),
    'access arguments' => array('reference top news'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function news_permission() {
  return array(
    'reference top news' => array(
      'title' => t('Reference top news item'),
      'description' => t('Use top item picker for news'),
    ),
  );
}

/**
 * Function to create settings form for each menu item
 * @return type
 */
function news_topitem_admin() {
  $form = array();

  global $user;
  $account = user_load($user->uid);
  $account_langs = array();
  if (isset($account->field_acc_language[LANGUAGE_NONE])) {
    foreach ($account->field_acc_language[LANGUAGE_NONE] as $lang) {
      $account_langs[] = $lang['value'];
    }
  }

  $languages = language_list('enabled');

  foreach ($languages[1] as $language) {

    // Check if user have access to language
    if (empty($account_langs) || in_array($language->language, $account_langs)) {

      $default_value = variable_get('news_topitem_'.$language->language, variable_get('news_topitem_en', FALSE));

      // default to US if none specified
      if (empty($default_value)) $default_value = variable_get('news_topitem_en', FALSE);

      if ($default_value && is_numeric($default_value)) {
        $node = node_load($default_value);
        if ($node) {
          $default_value = check_plain($node->title) . " [nid:$node->nid]";
        }
      }

      // Text field form element
      $form['news_topitem_'.$language->language] = array(
        '#type' => 'textfield',
        '#title' => t("Top item for " . $language->name),
        '#description' => t("Pick node for displaying in news overview page"),
        '#autocomplete_path' => 'jeeveserp-layout/topitem/news',
        '#default_value' => $default_value,
      );
    }
  }

  $form['#submit'][]='news_topitem_admin_submit';

  return system_settings_form($form);
}

function news_topitem_admin_submit($form, &$form_state){

  $languages = language_list('enabled');

  foreach ($languages[1] as $language) {
    $nid = 0;

    // extract nid from field value (if found)
    $pattern = '/^(?:\s*|(.*) )?\[\s*nid\s*:\s*(\d+)\s*\]$/';
    preg_match($pattern, $form_state['values']['news_topitem_'.$language->language], $matches);

    // if anything matches
    if (sizeof($matches) > 0) {

      // extract nid from last match
      if (is_numeric($matches[sizeof($matches) - 1])) {

        // let's save it, if nid is numeric
        $nid = $matches[sizeof($matches) - 1];
      }
    }

    // save value
    //variable_set('news_topitem_'.$language->language, $nid);
    $form_state['values']['news_topitem_'.$language->language] = $nid;

  }

  form_state_values_clean($form_state);
}

/**
 * Implements hook_block_info().
 */
function news_block_info() {
  $blocks = array(
    'news_topitem' => array(
      'info' => t('Top item picker'),
    ),
  );

  return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function news_block_configure($delta='') {
  global $language;

  $form = array();

  switch($delta) {

    case 'news_topitem':

      $default_value = variable_get('news_topitem_'.$language->language, variable_get('news_topitem_en', FALSE));

      // default to US if none specified
      if (empty($default_value)) $default_value = variable_get('news_topitem_en', FALSE);

      if ($default_value && is_numeric($default_value)) {
        $node = node_load($default_value);
        if ($node) {
          $default_value = check_plain($node->title) . " [nid:$node->nid]";
        }
      }

      // Text field form element
      $form['news_topitem'] = array(
        '#type' => 'textfield',
        '#title' => t("Top item"),
        '#description' => t("Pick node for displaying in news overview page"),
        '#autocomplete_path' => 'jeeveserp-layout/topitem/news',
        '#default_value' => $default_value,
      );

      break;
  }
  return $form;
}

function _news_topitem_autocomplete($string) {
  $matches = array();
  if ($string) {
    $result = db_select('node')
      ->fields('node', array('title', 'nid'))
      ->condition('type', 'news', '=')
      ->condition('title', '%' . db_like($string) . '%', 'LIKE')
      ->range(0, 10)
      ->execute();
    foreach ($result as $node) {
      $matches[check_plain($node->title) . " [nid:$node->nid]"] = check_plain($node->title) . " [nid:$node->nid]";
    }
  }

  drupal_json_output($matches);
}

/**
 * Implements hook_block_save().
 */
function news_block_save($delta = '', $edit = array()) {
  global $language;

  switch($delta) {

    case 'news_topitem' :

      $nid = 0;

      // extract nid from field value (if found)
      preg_match('/^(?:\s*|(.*) )?\[\s*nid\s*:\s*(\d+)\s*\]$/', $edit['news_topitem'], $matches);

      // if anything matches
      if (sizeof($matches) > 0) {

        // extract nid from last match
        if (is_numeric($matches[sizeof($matches) - 1])) {

          // let's save it, if nid is numeric
          $nid = $matches[sizeof($matches) - 1];
        }
      }

      // save value
      variable_set('news_topitem_'.$language->language, $nid);

      break;
  }
}

/**
 * Implements hook_block_view().
 */
function news_block_view($delta='') {
  $block = array();

  switch($delta) {

    case 'news_topitem' :
      $block['content'] = _news_topitem_view();
      break;
  }

  return $block;
}

/**
 * Custom function to assemble renderable array for block content.
 * Returns a renderable array with the block content.
 * @return
 *   returns a renderable array of block content.
 */
function _news_topitem_view() {

  global $language;

  $markup = '';
  $nid = variable_get('news_topitem_'.$language->language, variable_get('news_topitem_en', 0));

  // default to US if none specified
  if (empty($nid)) $nid = variable_get('news_topitem_en', FALSE);

  if ($nid > 0) $markup = views_embed_view('news', 'block_1', $nid);
  else {
    if (user_access('reference top news')) $markup = 'No news item promoted' . ', ' .l('pick one here', 'admin/content/topitem-news');
  }

  // Block output in HTML with div wrapper
  $block = array(
    'content' => array(
      'title' => '<none>',
      '#type' => 'markup',
      '#markup' => $markup,
    ),
  );

 return $block;
}
