<?php
/**
 * @file
 * Code for the Landing pages feature.
 */

include_once 'landing_pages.features.inc';


/**
 * Implements hook_menu_block_blocks().
 */
function landing_pages_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    '3' => array(
      'parent'      => 'menu-landing-pages:0',
      'title_link'  => 1,
      'admin_title' => 'Landing pages (level 2+)',
      'level'       => 2,
      'follow'      => '0',
      'depth'       => 2,
      'expanded'    => 1,
      'sort'        => 0,
    ),
  );
}
