<?php
/**
 * @file
 * jeeves_site_default.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function jeeves_site_default_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'Malmö, Sweden',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'ecb007a8-7a15-4082-a18b-250ba0d078d2',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398428107,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '03ca8912-c926-4339-b3b5-7573a3ef3c0b',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">Hyllie Boulevard&nbsp;17<br />215&nbsp;32 Malmö<br />SWEDEN</p><p style="color: rgb(112, 112, 112);">+46 (0)40 642 05 00<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">Hyllie Boulevard 17<br />215 32 Malmö<br />SWEDEN</p><p style="color: rgb(112, 112, 112);">+46 (0)40 642 05 00<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (12.9749534 55.5639436)',
        'geo_type' => 'point',
        'lat' => '55.563943600000',
        'lon' => '12.974953400000',
        'left' => '12.974953400000',
        'top' => '55.563943600000',
        'right' => '12.974953400000',
        'bottom' => '55.563943600000',
        'geohash' => 'u3chp7056mf6p',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => 'Hyllie Boulevard 17 215 32 Malmö SWEDEN',
        'format' => NULL,
        'safe_value' => 'Hyllie Boulevard 17 215 32 Malmö SWEDEN',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'regional',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Malmö, Sweden',
        'format' => NULL,
        'safe_value' => 'Malmö, Sweden',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => '3f5cacd42f4a8c630502a99492aa56e7',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:15:07 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Göteborg, Sweden',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '0c1d77a1-f236-4f89-895f-16ea7503a6f0',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398428025,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '0c826d4b-f0d9-4c6e-8d3d-9ddb5be5e230',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">Första Långgatan 26<br />413 28 Göteborg<br />SWEDEN</p><p style="color: rgb(112, 112, 112);">+46 (0)31 775 66 00<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">Första Långgatan 26<br />413 28 Göteborg<br />SWEDEN</p><p style="color: rgb(112, 112, 112);">+46 (0)31 775 66 00<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (11.9464302 57.6995192)',
        'geo_type' => 'point',
        'lat' => '57.699519200000',
        'lon' => '11.946430200000',
        'left' => '11.946430200000',
        'top' => '57.699519200000',
        'right' => '11.946430200000',
        'bottom' => '57.699519200000',
        'geohash' => 'u622pzgh5czyz',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => 'Första Långgatan 26 413 28 Göteborg SWEDEN',
        'format' => NULL,
        'safe_value' => 'Första Långgatan 26 413 28 Göteborg SWEDEN',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'regional',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Göteborg, Sweden',
        'format' => NULL,
        'safe_value' => 'Göteborg, Sweden',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => '53d15df21cfc9e1f08c2b4e58f3a0679',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:13:45 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'France',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '007a80c0-efaa-4be5-921c-ef06d2b950b6',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398427690,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '265fe9e2-38c3-41fb-bad5-17be3f3a3cae',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">33, Rue Galilée<br />75116&nbsp;Paris<br />FRANCE</p><p style="color: rgb(112, 112, 112);">0144435376<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">33, Rue Galilée<br />75116 Paris<br />FRANCE</p><p style="color: rgb(112, 112, 112);">0144435376<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (2.2949672 48.8694363)',
        'geo_type' => 'point',
        'lat' => '48.869436300000',
        'lon' => '2.294967200000',
        'left' => '2.294967200000',
        'top' => '48.869436300000',
        'right' => '2.294967200000',
        'bottom' => '48.869436300000',
        'geohash' => 'u09wh0rjhe5wd',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => '33, Rue Galilée 75116 Paris FRANCE',
        'format' => NULL,
        'safe_value' => '33, Rue Galilée 75116 Paris FRANCE',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'regional',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'France',
        'format' => NULL,
        'safe_value' => 'France',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => '2ea75dd040c2594cbd08b5a2526ea4d4',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:08:10 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Jönköping, Sweden',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '643effcc-9814-44b5-a9f3-bfc5060a298d',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398428054,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '649ad63e-0383-4426-a584-6f8faccc0328',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">Kaserngatan 14<br />553 05 Jönköping<br />SWEDEN</p><p style="color: rgb(112, 112, 112);">+46 (0)36 2100 100<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">Kaserngatan 14<br />553 05 Jönköping<br />SWEDEN</p><p style="color: rgb(112, 112, 112);">+46 (0)36 2100 100<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (14.2012286 57.7752915)',
        'geo_type' => 'point',
        'lat' => '57.775291500000',
        'lon' => '14.201228600000',
        'left' => '14.201228600000',
        'top' => '57.775291500000',
        'right' => '14.201228600000',
        'bottom' => '57.775291500000',
        'geohash' => 'u660ejtj2wgw1',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => 'Kaserngatan 14 553 05 Jönköping SWEDEN',
        'format' => NULL,
        'safe_value' => 'Kaserngatan 14 553 05 Jönköping SWEDEN',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'regional',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Jönköping, Sweden',
        'format' => NULL,
        'safe_value' => 'Jönköping, Sweden',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => '6ec5f46dd4aeab12bfbe02cec5c9a958',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:14:14 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Karlstad, Sweden',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'c799cf89-2cc1-4ead-b067-1a03907cf204',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398428082,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '81ada744-9894-4cee-a312-4726b60d46bb',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">Bryggaregatan 9<br />653 40<strong> </strong>Karlstad<br />SWEDEN</p><p style="color: rgb(112, 112, 112);">+46 (0)54 17 03 30<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">Bryggaregatan 9<br />653 40<strong> </strong>Karlstad<br />SWEDEN</p><p style="color: rgb(112, 112, 112);">+46 (0)54 17 03 30<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (13.4940398 59.3827499)',
        'geo_type' => 'point',
        'lat' => '59.382749900000',
        'lon' => '13.494039800000',
        'left' => '13.494039800000',
        'top' => '59.382749900000',
        'right' => '13.494039800000',
        'bottom' => '59.382749900000',
        'geohash' => 'u699g4619fvm5',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => 'Bryggaregatan 9 653 40 Karlstad SWEDEN',
        'format' => NULL,
        'safe_value' => 'Bryggaregatan 9 653 40 Karlstad SWEDEN',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'regional',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Karlstad, Sweden',
        'format' => NULL,
        'safe_value' => 'Karlstad, Sweden',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => '38b46aed9268020b212b0a680a483d16',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:14:42 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'United States',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '6e06d32e-b9df-4665-b7c6-8f75c77e4339',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398427627,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '99555b78-166a-4360-98e7-1f39c04e2d0d',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">7500 Rialto Blvd.<br />Building 2, Suite 230<br />Austin, TX&nbsp;78735<br />USA</p><p style="color: rgb(112, 112, 112);">+1 (512) 333-4418<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">7500 Rialto Blvd.<br />Building 2, Suite 230<br />Austin, TX 78735<br />USA</p><p style="color: rgb(112, 112, 112);">+1 (512) 333-4418<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (-97.8724088 30.2536557)',
        'geo_type' => 'point',
        'lat' => '30.253655700000',
        'lon' => '-97.872408800000',
        'left' => '-97.872408800000',
        'top' => '30.253655700000',
        'right' => '-97.872408800000',
        'bottom' => '30.253655700000',
        'geohash' => '9v6khge2rd4tc',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => '7500 Rialto Blvd #230 Austin, TX 78735',
        'format' => NULL,
        'safe_value' => '7500 Rialto Blvd #230 Austin, TX 78735',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'regional',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'United States',
        'format' => NULL,
        'safe_value' => 'United States',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => '06cb9a8a5f8a64b70b2c2cb67af500c9',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:07:07 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Norway',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'e36830fe-18b5-44b8-8b95-c6c6e1b7d7ef',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398427742,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'c89c6b12-b4e5-4484-9cc3-be3264ddf225',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">Thunes vei 2<br />0274 Oslo<br />NORWAY</p><p style="color: rgb(112, 112, 112);">+47 668 18 800<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">Thunes vei 2<br />0274 Oslo<br />NORWAY</p><p style="color: rgb(112, 112, 112);">+47 668 18 800<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (10.6889006 59.9220965)',
        'geo_type' => 'point',
        'lat' => '59.922096500000',
        'lon' => '10.688900600000',
        'left' => '10.688900600000',
        'top' => '59.922096500000',
        'right' => '10.688900600000',
        'bottom' => '59.922096500000',
        'geohash' => 'u4xsghrrt2muy',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => 'Thunes vei 2 0274 Oslo NORWAY',
        'format' => NULL,
        'safe_value' => 'Thunes vei 2 0274 Oslo NORWAY',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'regional',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Norway',
        'format' => NULL,
        'safe_value' => 'Norway',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => '36a370af9bed1041fb9329039f26b1db',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:09:02 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Headquarters',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '8e4dfbca-66c4-4c45-adfc-36a02eb5f545',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398427304,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'cd483622-08a2-4677-a758-5421604b0a84',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">World Trade Center<br />Kungsbron 1 /&nbsp;<br />Klarabergsviadukten 70<br />Sektion F - Plan 8<br />Box 1042<br />101 38 STOCKHOLM</p><p>+46 8 587 099 00</p><p><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">World Trade Center<br />Kungsbron 1 / <br />Klarabergsviadukten 70<br />Sektion F - Plan 8<br />Box 1042<br />101 38 STOCKHOLM</p><p>+46 8 587 099 00</p><p><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (18.057098 59.331194)',
        'geo_type' => 'point',
        'lat' => '59.331194000000',
        'lon' => '18.057098000000',
        'left' => '18.057098000000',
        'top' => '59.331194000000',
        'right' => '18.057098000000',
        'bottom' => '59.331194000000',
        'geohash' => 'u6scdbuv2bhn',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => 'Kungsbron 1 /  Klarabergsviadukten 70  101 38 STOCKHOLM',
        'format' => NULL,
        'safe_value' => 'Kungsbron 1 /  Klarabergsviadukten 70  101 38 STOCKHOLM',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'head',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Headquarters',
        'format' => NULL,
        'safe_value' => 'Headquarters',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => 'dceeddfe8dc1371414edd57aeed40b1f',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:01:44 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Borås, Sweden',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '0259b618-bb64-4c52-8d63-739cad13e4ae',
  'ds_switch' => '',
  'type' => 'office',
  'language' => 'en',
  'created' => 1398428135,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd707fcdb-ada1-4565-8884-140aabdf1ece',
  'revision_uid' => 1,
  'body' => array(
    'en' => array(
      0 => array(
        'value' => '<p style="color: rgb(112, 112, 112);">Göteborgsvägen 99<br />Box 396<br />504 60 Borås</p><p style="color: rgb(112, 112, 112);">033-44 41 00<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => ' <p style="color: rgb(112, 112, 112);">Göteborgsvägen 99<br />Box 396<br />504 60 Borås</p><p style="color: rgb(112, 112, 112);">033-44 41 00<br /><a href="mailto:info@jeeves.se">info@jeeves.se</a></p> ',
        'safe_summary' => '  ',
      ),
    ),
  ),
  'field_location' => array(
    'und' => array(
      0 => array(
        'geom' => 'POINT (12.9027247 57.7153239)',
        'geo_type' => 'point',
        'lat' => '57.715323900000',
        'lon' => '12.902724700000',
        'left' => '12.902724700000',
        'top' => '57.715323900000',
        'right' => '12.902724700000',
        'bottom' => '57.715323900000',
        'geohash' => 'u630mdg2pk0ve',
      ),
    ),
  ),
  'field_office_address' => array(
    'und' => array(
      0 => array(
        'value' => 'Göteborgsvägen 99 Box 396 504 60 Borås',
        'format' => NULL,
        'safe_value' => 'Göteborgsvägen 99 Box 396 504 60 Borås',
      ),
    ),
  ),
  'field_office_type' => array(
    'und' => array(
      0 => array(
        'value' => 'regional',
      ),
    ),
  ),
  'title_field' => array(
    'en' => array(
      0 => array(
        'value' => 'Borås, Sweden',
        'format' => NULL,
        'safe_value' => 'Borås, Sweden',
      ),
    ),
  ),
  'metatags' => array(),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'hash' => 'df23b260a3943844ca59577f0dd15524',
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-04-25 15:15:35 +0300',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Front page',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'bfeddd07-ed45-48ed-bd40-9e9701ebc9d6',
  'ds_switch' => '',
  'type' => 'full_page',
  'language' => 'en',
  'created' => 1391507125,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f5aef484-c96d-4e49-a794-c668e2d94c60',
  'revision_uid' => 1,
  'body' => array(),
  'field_page_sections' => array(
    'und' => array(
      0 => array(
        'target_id' => 1124,
      ),
      1 => array(
        'target_id' => 1122,
      ),
      2 => array(
        'target_id' => 1123,
      ),
      3 => array(
        'target_id' => 1136,
      ),
    ),
  ),
  'field_background_image' => array(),
  'metatags' => array(
    'en' => array(
      'title' => array(
        'value' => 'Jeeves ERP affärssystem',
      ),
      'description' => array(
        'value' => 'Välkommen till Jeeves ERP',
      ),
      'keywords' => array(
        'value' => 'affärssystem, erp, jeeves, garp, systemstöd, jeeves affärssystem, jeeves erp',
      ),
    ),
  ),
  'translations' => array(
    'original' => NULL,
    'data' => array(),
  ),
  'lingotek' => array(
    'name' => '',
    'document_id' => NULL,
    'lingotek_nodes_translation_method' => 'field',
    'create_lingotek_document' => 0,
    'sync_method' => 0,
    'allow_community_translation' => 0,
    'url_alias_translation' => 0,
    'node_sync_status' => 'EDITED',
    'project_id' => 24683,
    'workflow_id' => 'cee721bf-0119-40b9-932a-539091ff28d6',
    'vault_id' => 10543,
    'profile' => 'DISABLED',
  ),
  'name' => 'admin',
  'picture' => 0,
  'data' => 'a:2:{s:7:"overlay";i:1;s:25:"overlay_message_dismissed";i:1;}',
  'date' => '2014-02-04 11:45:25 +0200',
);
  return $nodes;
}
